spring.application.name=mini
server.port=8090

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# DB init
# spring.sql.init.mode=always
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Hibernate DDL auto setting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

mybatis.configuration.map-underscore-to-camel-case=true

# file location
spring.web.resources.static-locations=classpath:/static/,file:///C:/uploads/
file.store-photo-dir=C:/uploads/stores/
file.menu-photo-dir=C:/uploads/menus/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

logging.level.org.springframework.security=DEBUG


spring.mvc.format.time=HH:mm

spring.profiles.include=key